### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dudunegrinhu** [bigbrush/yii2-bigcms#2]
Do you have a demo link?

**Comment by bigbrush** [comment]
not yet, but i will create a demo site as soon as BIG CMS reaches a stable release. It is almost there. I will update here when a demo site is available.

**Comment by bigbrush** [comment]
no demo yet but i have updated the docs with an install guide. let me know if you try it out.

**Comment by bigbrush** [comment]
A demo site has now been created:  http://demo.bigbrush-agency.com/
