### ISSUE TITLE
frontend demo breakdown。

### ISSUE THREAD

**Issue by neatlife** [bigbrush/yii2-bigcms#20]

**Comment by bigbrush** [comment]
You are right - it's on my todo list, and priotized. No deadline set though.

**Comment by bigbrush** [comment]
I'm in the process of making tutorials for Big Cms.

https://github.com/bigbrush/yii2-cmf/blob/master/docs/introduction.md

**Comment by bigbrush** [comment]
The final documentation can be found here: http://www.bigbrush-agency.com/guide/
