### ISSUE TITLE
Backend demo wrong credentials

### ISSUE THREAD

**Issue by PVGrad** [bigbrush/yii2-bigcms#33]
In your [info](https://github.com/bigbrush/yii2-bigcms#demo-) about accessing Demo:
**Username**: bigadmin
**Password**: bigadmin
Provides "_Incorrect username or password._" message

**Comment by bigbrush** [comment]
Yeah people can change the credentials, which results in this. I will update the database later today when i have time.

**Comment by bigbrush** [comment]
Ooops shouldn't have closed it :)

**Comment by bigbrush** [comment]
I have updated the demo site, so you'll be able to log in with the provided credentials.

**Comment by PVGrad** [comment]
Thanks
