### ISSUE TITLE
cms/init Error SqlState

### ISSUE THREAD

**Issue by mysoundmagic** [bigbrush/yii2-bigcms#37]
i was run cms/init and apply migration there's error insert table category

insert into {{%category}} ...Error: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'created_at' at row 1
The SQL being executed was: INSERT INTO `category` (`id`, `module`, `title`, `content`, `state`, `tree`, `lft`, `rgt`, `depth`, `created_at`, `updated_at`, `alias`, `meta_title`, `meta_description`, `meta_keywords`, `params`) VALUES (1, 'pages', 'pages', '', 1, 1, 1, 4, 0, NOW(), NOW(), 'pages-root', '', '', '', '')

Error: SQLSTATE[HY000]: General error: 1364 Field 'template_id' doesn't have a default value
The SQL being executed was: INSERT INTO `category` (`id`, `module`, `title`, `content`, `state`, `tree`, `lft`, `rgt`, `depth`, `created_at`, `updated_at`, `alias`, `meta_title`, `meta_description`, `meta_keywords`, `params`) VALUES (1, 'pages', 'pages', '', 1, 1, 1, 4, 0, NOW(), NOW(), 'pages-root', '', '', '', '')

and another errors in migrations

**Comment by bigbrush** [comment]
Hmm, no problem here. But let me have a look at it and I will come back with something.

**Comment by bigbrush** [comment]
What database are you using?

**Comment by mysoundmagic** [comment]
I use mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) - ubuntu server 16.04.

**Comment by bigbrush** [comment]
I cannot replicate this error, so i dont know what is going on

**Comment by mysoundmagic** [comment]
@bigbrush , it's ok and thank you for response. i was change all create_at, update_at and all INT with BIGINT and Migration was succeed. close issue :+1:
